global:
  scrape_interval: 1s
  scrape_timeout: 1s

scrape_configs:
  - job_name: coders
    scrape_interval: 1s
    scrape_timeout: 1s
    static_configs:
      - targets:
          - php:9501 #funcionout     
          - php:9502 #funcionout     
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  
          